from peripherals.graphics.ST7735_driver import TFT

BLACK = TFT.BLACK
RED = TFT.RED
MAROON = TFT.MAROON
GREEN = TFT.GREEN
FOREST = TFT.FOREST
BLUE = TFT.BLUE
NAVY = TFT.NAVY
CYAN = TFT.CYAN
YELLOW = TFT.YELLOW
PURPLE = TFT.PURPLE
WHITE = TFT.WHITE
GRAY = TFT.GRAY

